# Ex1 - Filtering and Sorting Data



### Step 1. Import the necessary libraries

In [1]:
import numpy as np
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

In [ ]:
# csv --> coma separated values
# tsv --> tab (tabulador) separated values

In [2]:
archivo = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"

### Step 3. Assign it to a variable called chipo.

In [3]:
chipo = pd.read_csv(archivo, sep='\t')
chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

(4622, 5)

# Name of the max valued product

In [4]:
chipo.item_price = chipo.item_price.str[1:].astype(float)
chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75

In [6]:
chipo2 = chipo.copy()
chipo2

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75

In [24]:
chipo.loc[chipo['item_price'].idxmax(), 'item_name']

'Chips and Fresh Tomato Salsa'

In [6]:
max(chipo.item_price)

44.25

In [5]:
index = chipo.item_price.idxmax()
index

3598

In [6]:
# no quiero el pedido, sino todo el producto
x = chipo.item_price[chipo.item_price == max(chipo.item_price)]
x

3598    44.25
Name: item_price, dtype: float64

In [7]:
s = chipo[chipo.item_price == max(chipo.item_price)]
s

,order_id,quantity,item_name,choice_description,item_price
3598,1443,15,Chips and Fresh Tomato Salsa,NaN,44.25

In [8]:
chipo.item_name.nunique()

50

In [9]:
# podria ser
chipo[chipo.item_price == max(chipo.item_price)][['item_name', 'item_price', 'quantity']].drop_duplicates()

                         item_name  item_price  quantity
3598  Chips and Fresh Tomato Salsa       44.25        15

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75

3598    Chips and Fresh Tomato Salsa
Name: item_name, dtype: object

                         item_name
3598  Chips and Fresh Tomato Salsa

'Chips and Fresh Tomato Salsa'

### Step 4. How many products cost more than $10.00?

In [22]:
mascara = chipo['item_price'] > 10
chipo[mascara].item_name.unique()

<StringArray>
[                'Chicken Bowl',                'Steak Burrito',
              'Chicken Burrito',                'Barbacoa Bowl',
               'Veggie Burrito',                  'Veggie Bowl',
           'Chicken Soft Tacos',                   'Steak Bowl',
             'Carnitas Burrito',                'Carnitas Bowl',
             'Barbacoa Burrito',           'Chicken Salad Bowl',
        'Barbacoa Crispy Tacos',            'Veggie Salad Bowl',
         'Chicken Crispy Tacos',                'Chicken Salad',
             'Steak Salad Bowl',                         'Bowl',
            'Veggie Soft Tacos',          'Barbacoa Soft Tacos',
        'Carnitas Crispy Tacos',          'Carnitas Salad Bowl',
          'Barbacoa Salad Bowl', 'Chips and Fresh Tomato Salsa',
             'Steak Soft Tacos',          'Carnitas Soft Tacos',
           'Steak Crispy Tacos',          'Chips and Guacamole',
            '6 Pack Soft Drink',                'Bottled Water',
                'Side of Chips']
Length: 31, dtype: str

In [ ]:
products = chipo.item_name[(chipo.item_price > 10)].nunique() # nunique me dice cuantos
products

31

In [37]:
chipo['unity_price'] = chipo.item_price / chipo.quantity
chipo['unity_price']

0        2.39
1        3.39
2        3.39
3        2.39
4        8.49
        ...
4617    11.75
4618    11.75
4619    11.25
4620     8.75
4621     8.75
Name: unity_price, Length: 4622, dtype: float64

In [ ]:
products = chipo.item_name[(chipo.unity_price > 10.0)]
products.nunique()

25

In [24]:
(chipo.item_price > 10.0).any()

np.True_

31

### Step 5. What is the price of each item? 
###### print a data frame with only two columns item_name and item_price

In [18]:
# te agrupo por choice description y del resto me haces el máximo
chipo_description = chipo.groupby(["choice_description", "item_name"]).max()
chipo_description

,,order_id,quantity,item_price
choice_description,item_name,,,
"[Adobo-Marinated and Grilled Chicken, Pinto Beans, [Sour Cream, Salsa, Cheese, Cilantro-Lime Rice, Guacamole]]",Burrito,214,1,7.40
"[Adobo-Marinated and Grilled Chicken, [Sour Cream, Cheese, Cilantro-Lime Rice]]",Burrito,279,1,7.40
[Adobo-Marinated and Grilled Chicken],Crispy Tacos,217,1,7.40
"[Adobo-Marinated and Grilled Steak, [Sour Cream, Salsa, Cheese, Cilantro-Lime Rice, Guacamole]]",Bowl,279,1,7.40
[Adobo-Marinated and Grilled Steak],Crispy Tacos,217,1,7.40
...,...,...,...,...
"[[Tomatillo-Red Chili Salsa (Hot), Tomatillo-Green Chili Salsa (Medium)], [Rice, Black Beans, Cheese, Lettuce]]",Chicken Burrito,1267,1,8.49
"[[Tomatillo-Red Chili Salsa (Hot), Tomatillo-Green Chili Salsa (Medium)], [Rice, Black Beans, Lettuce]]",Chicken Bowl,1215,1,8.49
"[[Tomatillo-Red Chili Salsa (Hot), Tomatillo-Green Chili Salsa (Medium)], [Rice, Pinto Beans, Cheese, Lettuce]]",Chicken Burrito,51,1,8.49
"[[Tomatillo-Red Chili Salsa (Hot), Tomatillo-Green Chili Salsa (Medium)], [Rice, Pinto Beans, Fajita Veggies, Cheese, Sour Cream, Lettuce]]",Barbacoa Bowl,51,1,8.99
"[[Tomatillo-Red Chili Salsa (Hot), Tomatillo-Green Chili Salsa (Medium)], [Rice, Pinto Beans, Fajita Veggies, Lettuce]]",Barbacoa Bowl,1299,1,8.99

In [31]:
chipo[['item_name', 'item_price']]

                                  item_name  item_price
0              Chips and Fresh Tomato Salsa        2.39
1                                      Izze        3.39
2                          Nantucket Nectar        3.39
3     Chips and Tomatillo-Green Chili Salsa        2.39
4                              Chicken Bowl       16.98
...                                     ...         ...
4617                          Steak Burrito       11.75
4618                          Steak Burrito       11.75
4619                     Chicken Salad Bowl       11.25
4620                     Chicken Salad Bowl        8.75
4621                     Chicken Salad Bowl        8.75

[4622 rows x 2 columns]

                         item_name  item_price
3598  Chips and Fresh Tomato Salsa       44.25
3480                 Carnitas Bowl       35.25
1254               Chicken Burrito       35.00
3602               Chicken Burrito       35.00
3601                Veggie Burrito       33.75
...                            ...         ...
3936                   Canned Soda        1.09
2922                 Bottled Water        1.09
1396                   Canned Soda        1.09
2562                   Canned Soda        1.09
1457                   Canned Soda        1.09

[4622 rows x 2 columns]

### Step 6. Sort by the name of the item

In [27]:
chipo3 = chipo.sort_values(by='item_name')
chipo3

,order_id,quantity,item_name,choice_description,item_price
3389,1360,2,6 Pack Soft Drink,[Diet Coke],12.98
341,148,1,6 Pack Soft Drink,[Diet Coke],6.49
1849,749,1,6 Pack Soft Drink,[Coke],6.49
1860,754,1,6 Pack Soft Drink,[Diet Coke],6.49
2713,1076,1,6 Pack Soft Drink,[Coke],6.49
...,...,...,...,...,...
2384,948,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75
781,322,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",8.75
2851,1132,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49
1699,688,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
1395,567,1,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49

,order_id,quantity,item_name,choice_description,item_price
3389,1360,2,6 Pack Soft Drink,[Diet Coke],12.98
341,148,1,6 Pack Soft Drink,[Diet Coke],6.49
1849,749,1,6 Pack Soft Drink,[Coke],6.49
1860,754,1,6 Pack Soft Drink,[Diet Coke],6.49
2713,1076,1,6 Pack Soft Drink,[Coke],6.49
...,...,...,...,...,...
2384,948,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75
781,322,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",8.75
2851,1132,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49
1699,688,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
1395,567,1,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49

### Step 7. What was the quantity of the most expensive item ordered? 2 ways

In [28]:
# cantidad del item más caro
max_value = chipo['item_price'].max()
max_value

np.float64(44.25)

V1

15

V2

item_price    44.25
quantity      15.00
dtype: float64

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [7]:
chipo.groupby('item_name')['quantity'].value_counts()

item_name              quantity
6 Pack Soft Drink      1           53
                       2            1
Barbacoa Bowl          1           66
Barbacoa Burrito       1           91
Barbacoa Crispy Tacos  1           10
                                   ..
Veggie Crispy Tacos    1            1
Veggie Salad           1            6
Veggie Salad Bowl      1           18
Veggie Soft Tacos      1            6
                       2            1
Name: count, Length: 103, dtype: int64

In [39]:
chipo_salad = chipo[chipo.item_name == "Veggie Salad Bowl"]
len(chipo_salad)

18

In [40]:
chipo.where(chipo.item_name == "Veggie Salad Bowl").groupby("item_name").sum()

,order_id,quantity,choice_description,item_price,unity_price
item_name,,,,,
Veggie Salad Bowl,17303.0,18.0,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",182.5,182.5

18

### Step 9. How many times did someone order more than one Canned Soda?

In [8]:
chipo.groupby(['item_name', 'choice_description'])['quantity'].value_counts()

item_name          choice_description                                                                                                 quantity
6 Pack Soft Drink  [Coke]                                                                                                             1           21
                   [Diet Coke]                                                                                                        1           23
                                                                                                                                      2            1
                   [Lemonade]                                                                                                         1            2
                   [Nestea]                                                                                                           1            2
                                                                                                                                                  ..
Veggie Soft Tacos  [Fresh Tomato Salsa, [Black Beans, Cheese, Sour Cream, Lettuce]]                                                   1            1
                   [Fresh Tomato Salsa, [Fajita Vegetables, Rice, Black Beans, Pinto Beans, Cheese, Sour Cream, Guacamole, Lettuce]]  1            1
                   [Roasted Chili Corn Salsa (Medium), [Black Beans, Fajita Veggies, Cheese, Sour Cream, Lettuce]]                    1            1
                   [Roasted Chili Corn Salsa, [Fajita Vegetables, Black Beans, Pinto Beans, Cheese, Lettuce]]                         1            1
                   [Tomatillo Red Chili Salsa, [Fajita Vegetables, Rice, Black Beans, Cheese, Guacamole, Lettuce]]                    1            1
Name: count, Length: 1915, dtype: int64

In [41]:
chipo_drink_steak_bowl = chipo[(chipo.item_name == "Canned Soda") & (chipo.quantity > 1)]
len(chipo_drink_steak_bowl)

20

20