# Introducing Pandas Objects

At the very basic level, Pandas objects can be thought of as **enhanced versions of NumPy structured arrays in which the rows and columns are identified with labels rather than simple integer indices.**
As we will see during the course of this chapter, Pandas provides a host of useful tools, methods, and functionality on top of the basic data structures, but **nearly everything that follows will require an understanding of what these structures are**.
Thus, before we go any further, let's introduce these three fundamental Pandas data structures: the ``Series``, ``DataFrame``, and ``Index``.

We will start our code sessions with the standard NumPy and Pandas imports:

In [ ]:
# ! pip install pandas  --> usa el pip, el primero que encuentre entre los varios que tengos
# %pip install pandas --> le estoy diciendo que use el pip de este jupyter notebook

In [1]:
import numpy as np
import pandas as pd

## The Pandas Series Object

A Pandas ``Series`` is a one-dimensional array of indexed data.
It can be created from a list or array as follows:

In [2]:
# Heights of class
data = pd.Series([1.5, 1.6, 1.75, 1.8]) # pd es pandas, al igual que numpy es np.
data

0    1.50
1    1.60
2    1.75
3    1.80
dtype: float64

In [3]:
# si ponemos Series, da errorr porque no saber que es. Esto es porque dentro de Pandas tengo series, pero está dentro de pandas
Series

NameError: name 'Series' is not defined

In [4]:
pd.Series

pandas.Series

In [5]:
type(pd.Series) # el tipo de panda.series, es tipo porque es una clase.

type

In [6]:
pd.Series() # si lo ejecuto, me da una serie vacia. Una serie es de una sola dimension.

Series([], dtype: object)

In [7]:
# Las series van a tener indexing y slicing.
data[[0]]

0    1.5
dtype: float64

In [8]:
data[0,1] # da error porque le estoy dando fila y columna, que son 2 dimensiones. Y las series solo tienen una dimension

KeyError: 'key of type tuple not found and not a MultiIndex'

In [9]:
data[:] # veré todo

0    1.50
1    1.60
2    1.75
3    1.80
dtype: float64

In [10]:
data[[0,1]]

0    1.5
1    1.6
dtype: float64

In [11]:
data.values # así se ve el numpy que hay dentro

array([1.5 , 1.6 , 1.75, 1.8 ])

In [12]:
data.values

array([1.5 , 1.6 , 1.75, 1.8 ])

As we see in the output, the ``Series`` wraps both a sequence of values and a sequence of indices, which we can access with the ``values`` and ``index`` attributes.
The ``values`` are simply a familiar NumPy array:

In [13]:
data = pd.Series([1.5, 1.6, 1.75, 1.8, "hola"])
data

0     1.5
1     1.6
2    1.75
3     1.8
4    hola
dtype: object

In [14]:
data[0] + data[1]

3.1

In [16]:
data[[0]] # esto es indexing

0    1.5
dtype: object

In [15]:
data[3:] # es slicing, toma el trozo empezando desde el 3 y llega hasta el final

3     1.8
4    hola
dtype: object

In [17]:
data[2:] # un trozo de una serie, es una serie

2    1.75
3     1.8
4    hola
dtype: object

In [18]:
data.values

array([1.5, 1.6, 1.75, 1.8, 'hola'], dtype=object)

The ``index`` is an array-like object of type ``pd.Index``, which we'll discuss in more detail momentarily.

In [19]:
type(data)

pandas.Series

In [20]:
data.index # data es una serie (es una dimensión, fila o columna por ejemplo), y llama al método index.

RangeIndex(start=0, stop=5, step=1)

Like with a NumPy array, data can be accessed by the associated index via the familiar Python square-bracket notation:

In [21]:
data[0]

1.5

In [22]:
#type(data.values[0])

In [23]:
data[1:3]

1     1.6
2    1.75
dtype: object

In [24]:
data[-1::-1]#[0]

4    hola
3     1.8
2    1.75
1     1.6
0     1.5
dtype: object

In [ ]:
# hay dos métodos que son el loc y el iloc que nos ayudan un monton

As we will see, though, **the Pandas ``Series`` is much more general and flexible than the one-dimensional NumPy** array that it emulates.

### ``Series`` as generalized NumPy array

From what we've seen so far, it may look like the ``Series`` object is basically interchangeable with a one-dimensional NumPy array.
**The essential difference is the presence of the index**: while the Numpy Array has an *implicitly defined* integer index used to access the values, the Pandas ``Series`` has an ***explicitly defined*** index associated with the values.

This explicit index definition gives the ``Series`` object additional capabilities. For example, the index need not be an integer, but can consist of values of any desired type.
For example, **if we wish, we can use strings as an index:**

In [25]:
data = pd.Series([1.5, 1.6, 1.75, 1.80], # todos los valoeres de una serie tienen que tener un index, otra cosa es que tenga un valor missing
                 index=['Jane', 'Joe', 'Susan', 'Mike'])

data

Jane     1.50
Joe      1.60
Susan    1.75
Mike     1.80
dtype: float64

In [54]:
data["Mike, Joe"] # esto da error porque son 2 dimensiones lo que estoy pidiendo pero las series son de una sola dimension

KeyError: 'Mike, Joe'

In [55]:
data[["Mike", "Joe"]] # esto es un objeto, porque es una lista

KeyError: "None of [Index(['Mike', 'Joe'], dtype='str')] are in the [index]"

In [26]:
data['Jane'] # esto es indexing, porque le estoy diciendo que vaya a 'Jane'

np.float64(1.5)

In [27]:
data['Jane':'Joe'] # empieza en Jane pero ahora sí que llega a Joe. Porque el índice es implícito no explícito.
# es lo mismo que si hibiera hecho data.loc['Jane':'Joe']

Jane    1.5
Joe     1.6
dtype: float64

In [28]:
data['Jane'] == 1.5

np.True_

In [29]:
data.index # esto es un objeto index

Index(['Jane', 'Joe', 'Susan', 'Mike'], dtype='str')

In [30]:
data

Jane     1.50
Joe      1.60
Susan    1.75
Mike     1.80
dtype: float64

In [31]:
data["Mike":"Joe":-1] # start: Mike, end: Joe, step: -1 (y vete para atrás)

Mike     1.80
Susan    1.75
Joe      1.60
dtype: float64

In [32]:
data["Mike":"Joe":1] # empieza en Mike, termina en Joe y vete hacia delante. Como no hay, te devuelve la serie vacía

Series([], dtype: float64)

In [34]:
data.loc[0:2:1] # se rompe porque estás buscando los valores
data.iloc[0:2:1] # te lo devuelve porque estás trabajando con los índices

TypeError: cannot do slice indexing on Index with these indexers [0] of type int

In [35]:
data["Joe":"Mike"]

Joe      1.60
Susan    1.75
Mike     1.80
dtype: float64

In [36]:
data["Joe":"Mike":-1]

Series([], dtype: float64)

In [37]:
data["Mike":"Joe"]

Series([], dtype: float64)

In [38]:
data

Jane     1.50
Joe      1.60
Susan    1.75
Mike     1.80
dtype: float64

In [39]:
data[-1:0:-1]

Mike     1.80
Susan    1.75
Joe      1.60
dtype: float64

In [40]:
test = pd.Series([1,2,3,4,5,6], index = ["Alberto", "Joe", "Mary", "Joe", "Peter", "Joe"])
test

Alberto    1
Joe        2
Mary       3
Joe        4
Peter      5
Joe        6
dtype: int64

In [41]:
#test["Alberto":"Joe"] # no puedes hacer slicing para índices no únicos
test["Joe"]

Joe    2
Joe    4
Joe    6
dtype: int64

In [42]:
data[1:3]

Joe      1.60
Susan    1.75
dtype: float64

And the item access works as expected:

In [43]:
data['Susan']

print(data['Susan'])
print(data.iloc[2])
print(data.iloc[0:2])
print(data['Jane':'Susan'])

1.75
1.75
Jane    1.5
Joe     1.6
dtype: float64
Jane     1.50
Joe      1.60
Susan    1.75
dtype: float64

We can even use non-contiguous or non-sequential indices:

In [44]:
data = pd.Series([1.5, 1.6, 1.75, 1.80],
                 index=[2, 5, 3, 7])
data

2    1.50
5    1.60
3    1.75
7    1.80
dtype: float64

In [45]:
data[2:5]

3    1.75
7    1.80
dtype: float64

In [56]:
s2 = pd.Series([1,2,3,4,5], index=[0,1,2,1,0])
s2

0    1
1    2
2    3
1    4
0    5
dtype: int64

In [ ]:
s2.loc[0].iloc[-1:] # loc entras por valor; iloc entras por indices

0    5
dtype: int64

### Series as specialized dictionary

In this way, you can think of a **Pandas ``Series`` a bit like a specialization of a Python dictionary.**
A dictionary is a structure that maps arbitrary keys to a set of arbitrary values, and a ``Series`` is a structure which maps typed keys to a set of typed values.
This typing is important: just as the type-specific compiled code behind a NumPy array makes it more efficient than a Python list for certain operations, the type information of a Pandas ``Series`` makes it much more efficient than Python dictionaries for certain operations.

The ``Series``-as-dictionary analogy can be made even more clear by constructing a ``Series`` object directly from a Python dictionary:

In [46]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [47]:
# como hacer una serie a partir de un diccionario
s1 = pd.Series([4,4,4,5])
s1

0    4
1    4
2    4
3    5
dtype: int64

By default, a ``Series`` will be created where the index is drawn from the sorted keys.
From here, typical dictionary-style item access can be performed:

In [48]:
population['California'] # accedo con indexing

np.int64(38332521)

In [49]:
s2 = pd.Series([1,2,3,4,5], index = ["Madrid", "California", "Japón", "California", "California"])
s2

Madrid        1
California    2
Japón         3
California    4
California    5
dtype: int64

In [50]:
s2["California"] # me dan una serie, me está devolviendo todos los índices California (te da un 2,4, 5) es una lista

California    2
California    4
California    5
dtype: int64

In [51]:
max(s2["California"])

5

In [52]:
s2["Madrid"] # solo obtengo el valor, porque solo es 1

np.int64(1)

Unlike a dictionary, though, the ``Series`` also supports array-style operations such as slicing:

In [53]:
population['California':'Illinois']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

We'll discuss some of the quirks of Pandas indexing and slicing in [Data Indexing and Selection](03.02-Data-Indexing-and-Selection.ipynb).

### Constructing Series objects

We've already seen a few ways of constructing a Pandas ``Series`` from scratch; all of them are some version of the following:

```python
>>> pd.Series(data, index=index)
```

where ``index`` is an optional argument, and ``data`` can be one of many entities.

For example, ``data`` can be a list or NumPy array, in which case ``index`` defaults to an integer sequence:

In [60]:
pd.Series([2,3,6])

0    2
1    3
2    6
dtype: int64

``data`` can be a scalar, which is repeated to fill the specified index:

In [61]:
pd.Series(5, index=[100, 200, 300])

100    5
200    5
300    5
dtype: int64

``data`` can be a dictionary, in which ``index`` defaults to the sorted dictionary keys:

In [62]:
pd.Series({2:'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: str

In each case, the index can be explicitly set if a different result is preferred:

In [63]:
p = pd.Series({2:'a', 1:'b', 3:'c'}, index=[3, 2])
p

3    c
2    a
dtype: str

In [64]:
p = pd.Series({2:'a', 1:'b', 3:'c'}, index=[3, 2,1])
p[0:2][2]

'a'

Notice that in this case, the ``Series`` is populated only with the explicitly identified keys.

## The Pandas DataFrame Object

The next fundamental structure in Pandas is the ``DataFrame``.
Like the ``Series`` object discussed in the previous section, the ``DataFrame`` can be **thought of either as a generalization of a NumPy array, or as a specialization of a Python dictionary.**
We'll now take a look at each of these perspectives.

### DataFrame as a generalized NumPy array
If a ``Series`` is an analog of a one-dimensional array with flexible indices, a **``DataFrame`` is an analog of a two-dimensional array with both flexible row indices and flexible column names.**
Just as you might think of a two-dimensional array as an ordered sequence of aligned one-dimensional columns, you can think of a ``DataFrame`` as a sequence of aligned ``Series`` objects.
Here, by "aligned" we mean that **they share the same index.**

To demonstrate this, let's first construct a new ``Series`` listing the area of each of the five states discussed in the previous section:

In [76]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [68]:
mi_df = pd.DataFrame() # te da un dataframe vacio
mi_df

Empty DataFrame
Columns: []
Index: []

In [67]:
mi_df = pd.DataFrame() # te da un dataframe vacio

mi_df['nombre'] = ["Alberto", "Pablo"]
mi_df

    nombre
0  Alberto
1    Pablo

In [72]:
mi_df['nombre'] = ["Alberto", "Pablo"] # un dataframe siempre tiene 2 dimensiones
mi_df['apellido'] = ["Romero", "da Cunha"]
mi_df['color'] = ["rojo", "verde"]
mi_df

    nombre  apellido  color
0  Alberto    Romero   rojo
1    Pablo  da Cunha  verde

Now that we have this along with the ``population`` Series from before, we can use a dictionary to construct a single two-dimensional object containing this information:

In [77]:
states = pd.DataFrame({'population': population,
                       'area': area})
states

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [78]:
type(states)

pandas.DataFrame

In [79]:
states.values

array([[38332521,   423967],
       [26448193,   695662],
       [19651127,   141297],
       [19552860,   170312],
       [12882135,   149995]])

Like the ``Series`` object, the ``DataFrame`` has an ``index`` attribute that gives access to the index labels:

In [80]:
states.head() # si lo ejecitp me da solo las filas.

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [81]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='str')

Additionally, the ``DataFrame`` has a ``columns`` attribute, which is an ``Index`` object holding the column labels:

In [82]:
states.columns[:1]

Index(['population'], dtype='str')

In [83]:
states.head(3)

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297

In [44]:
midf = pd.DataFrame()
midf['temperatura'] = [1,2,3]
midf

   temperatura
0            1
1            2
2            3

**Thus the ``DataFrame`` can be thought of as a generalization of a two-dimensional NumPy array, where both the rows and columns have a generalized index for accessing the data.**

In [84]:
s4 = pd.Series([4,5,6])
s5 = s4 * 2
s6 = s4 * 3

pd.DataFrame([s4, s5, s6])

    0   1   2
0   4   5   6
1   8  10  12
2  12  15  18

In [87]:
a = pd.DataFrame(s4, columns= ["A"])
b = pd.DataFrame(s4, columns= ["B"])
c = pd.DataFrame(s4, columns= ["C"])
pd.concat([a,b,c], axis=0)

     A    B    C
0  4.0  NaN  NaN
1  5.0  NaN  NaN
2  6.0  NaN  NaN
0  NaN  4.0  NaN
1  NaN  5.0  NaN
2  NaN  6.0  NaN
0  NaN  NaN  4.0
1  NaN  NaN  5.0
2  NaN  NaN  6.0

### DataFrame as specialized dictionary

Similarly, we can also think of a ``DataFrame`` as a specialization of a dictionary.
Where a dictionary maps a key to a value, a ``DataFrame`` maps a column name to a ``Series`` of column data.
For example, asking for the ``'area'`` attribute returns the ``Series`` object containing the areas we saw earlier:

In [45]:
states['population']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
Name: population, dtype: int64

In [46]:
states['area'].name

'area'

**Notice the potential point of confusion here: in a two-dimesnional NumPy array, ``data[0]`` will return the first *row*. For a ``DataFrame``, ``data['col0']`` will return the first *column*.**
Because of this, it is probably better to think about ``DataFrame``s as generalized dictionaries rather than generalized arrays, though both ways of looking at the situation can be useful.
We'll explore more flexible means of indexing ``DataFrame``s in [Data Indexing and Selection](03.02-Data-Indexing-and-Selection.ipynb).

### Constructing DataFrame objects

A Pandas ``DataFrame`` can be constructed in a variety of ways.
Here we'll give several examples.

#### From a single Series object

A ``DataFrame`` is a collection of ``Series`` objects, and a single-column ``DataFrame`` can be constructed from a single ``Series``:

In [47]:
pd.DataFrame(population, columns=['population'])

            population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

In [48]:
pd.DataFrame(population, columns=['population'])['population']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
Name: population, dtype: int64

In [49]:
states.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

#### From a list of dicts

Any list of dictionaries can be made into a ``DataFrame``.
We'll use a simple list comprehension to create some data:

In [50]:
data = [{'a': i, 'b': 2 * i} for i in range(3)]
pd.DataFrame(data)
# [{'a':0, 'b':0}, {'a':1, 'b':2}, {'a':2, 'b':4}]

   a  b
0  0  0
1  1  2
2  2  4

In [51]:
{  x : x*2   for x   in [1,2,3]   }

{1: 2, 2: 4, 3: 6}

In [52]:
[    x*2  if x ==2 or x == 1 else 10  for x  in [1,2,3]    ]  # list comprehension

[2, 4, 10]

In [53]:
l = []
for x in [1,2,3]:
    l.append(x*2)
l

[2, 4, 6]

In [54]:
[   x+1  for x in [1,2,3,9] ]

[2, 3, 4, 10]

In [55]:
{x: "letra: " + x for x in ['a','b','c']} # dict comprehesion

{'a': 'letra: a', 'b': 'letra: b', 'c': 'letra: c'}

Even if some keys in the dictionary are missing, Pandas will fill them in with ``NaN`` (i.e., "not a number") values:

In [56]:
import pandas as pd
import numpy as np

midic1 = {'a': 1, 'b': 2}
midic2 = {'b': 3, 'c': 4}

midf = pd.DataFrame(data = [midic1, midic2])

midf = pd.DataFrame( data = [midic1, midic2])
midf.index = ["hola", "adiós"]
midf

         a  b    c
hola   1.0  2  NaN
adiós  NaN  3  4.0

In [57]:
pd.DataFrame([{'a': "hola", 'b': 2}, { 'a': 1, 'b': 3, 'c': 4}]).dtypes

a     object
b      int64
c    float64
dtype: object

In [58]:
type(pd.DataFrame([{'a': "hola", 'b': 2},
                   { 'a': 1, 'b': 3, 'c': 4}])
     .values[1][0])

int

In [59]:
pd.DataFrame([{'a': "hola", 'b': 2},
                   { 'a': 1, 'b': 3, 'c': 4}])\
     .values[0][1]

2

In [60]:
"lalala\nlelele"
"""lalala\nlelele
lololo"""

'lalala\nlelele\nlololo'

In [61]:
type(pd.DataFrame([{'a': "hola", 'b': 2},
                   { 'a': 1, 'b': 3, 'c': 4}]).values[1][0])

int

In [62]:
np.array([5]).dtype

dtype('int64')

In [63]:
type(np.array([5])[0])

numpy.int64

In [64]:
print(
 "hola\
 qué\
 tal" 
)

hola qué tal

In [65]:
# 1.8   1.80  1.8000000000000001
# 8   8.

In [66]:
np.inf

inf

In [67]:
float('inf')

inf

In [68]:
np.nan

nan

#### From a dictionary of Series objects

As we saw before, a ``DataFrame`` can be constructed from a dictionary of ``Series`` objects as well:

In [69]:
pd.DataFrame({'population': population,
              'area': area})

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

#### From a two-dimensional NumPy array

Given a two-dimensional array of data, we can create a ``DataFrame`` with any specified column and index names.
If omitted, an integer index will be used for each:

In [70]:
pd.DataFrame(np.random.rand(3, 2),
             columns=['foo', 'bar'],
             index=['a', 'b', 'c'])

        foo       bar
a  0.209052  0.825613
b  0.404764  0.000172
c  0.277732  0.692014

#### From a NumPy structured array

We covered structured arrays in [Structured Data: NumPy's Structured Arrays](02.09-Structured-Data-NumPy.ipynb).
A Pandas ``DataFrame`` operates much like a structured array, and can be created directly from one:

In [71]:
import numpy as np
A = np.zeros(3, dtype=[('A', 'i8'), ('B', 'f8'), ('C', 'f8')])
A

array([(0, 0., 0.), (0, 0., 0.), (0, 0., 0.)],
      dtype=[('A', '<i8'), ('B', '<f8'), ('C', '<f8')])

In [72]:
pd.DataFrame(A)

   A    B    C
0  0  0.0  0.0
1  0  0.0  0.0
2  0  0.0  0.0

## The Pandas Index Object

We have seen here that both the ``Series`` and ``DataFrame`` objects contain an explicit *index* that lets you reference and modify data.
This ``Index`` object is an interesting structure in itself, and **it can be thought of either as an *immutable array* or as an *ordered set* (technically a multi-set, as ``Index`` objects may contain repeated values).**
Those views have some interesting consequences in the operations available on ``Index`` objects.
As a simple example, let's construct an ``Index`` from a list of integers:

In [73]:
ind = pd.Index([2, 3, 5, 7, 11])
ind

Index([2, 3, 5, 7, 11], dtype='int64')

### Index as immutable array

The ``Index`` in many ways operates like an array.
For example, we can use standard Python indexing notation to retrieve values or slices:

In [74]:
ind[1]

np.int64(3)

In [75]:
ind[::2]

Index([2, 5, 11], dtype='int64')

``Index`` objects also have many of the attributes familiar from NumPy arrays:

In [76]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64

One difference between ``Index`` objects and NumPy arrays is that indices are immutable–that is, they cannot be modified via the normal means:

In [77]:
ind[1] = 0

TypeError: Index does not support mutable operations

**This immutability makes it safer to share indices between multiple ``DataFrame``s and arrays, without the potential for side effects from inadvertent index modification.**

### Index as ordered set

Pandas objects are designed to facilitate operations such as joins across datasets, which depend on many aspects of set arithmetic.
**The ``Index`` object follows many of the conventions used by Python's built-in ``set`` data structure, so that unions, intersections, differences, and other combinations can be computed in a familiar way:**

In [78]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

In [79]:
indA & indB  # intersection

Index([0, 3, 5, 7, 9], dtype='int64')

In [80]:
indA.intersection(indB)

Index([3, 5, 7], dtype='int64')

In [81]:
indA.intersection(indB)
indA.__and__(indB) # indA & indB

Index([0, 3, 5, 7, 9], dtype='int64')

In [82]:
indA | indB  # union

Index([3, 3, 5, 7, 11], dtype='int64')

In [83]:
testindA = pd.Index([1,2,3,3,3,3,3,3])
testindB = pd.Index([2,3,1,5, 5, 1])
testindA.union(testindB)

Index([1, 1, 2, 3, 3, 3, 3, 3, 3, 5, 5], dtype='int64')

In [84]:
indA ^ indB  # symmetric difference

Index([3, 0, 0, 0, 2], dtype='int64')

These operations may also be accessed via object methods, for example ``indA.intersection(indB)``.