# Combining Datasets: Concat and Append

Some of the most interesting studies of data come from combining different data sources.
These operations can involve anything from very straightforward concatenation of two different datasets, to more complicated database-style joins and merges that correctly handle any overlaps between the datasets.
``Series`` and ``DataFrame``s are built with this type of operation in mind, and Pandas includes functions and methods that make this sort of data wrangling fast and straightforward.

Here we'll take a look at simple concatenation of ``Series`` and ``DataFrame``s with the ``pd.concat`` function; later we'll dive into more sophisticated in-memory merges and joins implemented in Pandas.

We begin with the standard imports:

In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.DataFrame([1,2,3,4],index = [1,3,2,4])
df

   0
1  1
3  2
2  3
4  4

In [ ]:
import numpy as np
import pandas as pd
df = pd.DataFrame([1,2,3,4],index = [1,3,2,4]) 
df.loc[1:3] # el loc busca por valores, por lo que busca el valor 1 esté donde esté hasta el valor 3 esté donde esté

   0
1  1
3  2

In [ ]:
df = pd.DataFrame([1,2,3])
df2 = df.copy()
pd.concat( [df, df2]) # cuando hago un concat, es lo mismo que poner axis=0 pd.concat( [df, df2], axis=0) y lo que hace es añadir datos en las filas (es concatenar)

   0
0  1
1  2
2  3
0  1
1  2
2  3

In [ ]:
pd.concat( [df, df2], axis=1) # al tener axis igual a 1 lo que haces es añadir columnas. Para meter más columnas, le mete un 0 para meter más columnas

   0  0
0  1  1
1  2  2
2  3  3

In [ ]:
df1 = pd.DataFrame([[1,2,3,4], [4,3,2,1]], columns = ["A", "B", "C", "D"])
df2 = pd.DataFrame([[5,6,7,8]], columns = ["A", "B", "C", "D"])
pd.concat([df1, df2], axis = 0) # quiero calcular la media (mean)

   A  B  C  D
0  1  2  3  4
1  4  3  2  1
0  5  6  7  8

In [ ]:
pd.concat([df1, df2], axis = 0).mean() # dejo la columna quieta y cojo la media de las filas. Si no digo nada, siempre es axis=0

A    3.333333
B    3.666667
C    4.000000
D    4.333333
dtype: float64

In [ ]:
pd.concat([df1, df2], axis = 1).mean() # dejo la fila quieta y cojo la media de las columnas

A    2.5
B    2.5
C    2.5
D    2.5
A    5.0
B    6.0
C    7.0
D    8.0
dtype: float64

In [12]:
pd.concat([df1, df2], axis = 0)

   A  B  C  D
0  1  2  3  4
1  4  3  2  1
0  5  6  7  8

In [ ]:
pd.concat([df1, df2]).stack() # tiene un axis=0. stack es para apilar. Pasa de Dataframe a Serie, y tengo indice multinivel
# squeeze es compactar, por lo que me da una serie. El dataframe tiene 12 elementos, por lo que la serie tiene que tener 12 elementos

0  A    1
   B    2
   C    3
   D    4
1  A    4
   B    3
   C    2
   D    1
0  A    5
   B    6
   C    7
   D    8
dtype: int64

In [ ]:
pd.concat([df1, df2]).stack()[0] # me quiero el indice 0, pero tengo 2 indices 0s

A    1
B    2
C    3
D    4
A    5
B    6
C    7
D    8
dtype: int64

In [19]:
df1

   A  B  C  D
0  1  2  3  4
1  4  3  2  1

In [20]:
df2

   A  B  C  D
0  5  6  7  8

In [ ]:
df3 = pd.concat([df1, df2], axis=0)
df3.reset_index(inplace=False) # lo que hago es resetear el index, pero te devuelve una copia modificada del DataFrame (porque inplace=False, por defecto). 
#Todo lo implique una modificacion permanente del original, te devuelve una copia por defecto a no ser que le indiques lo contrario

   index  A  B  C  D
0      0  1  2  3  4
1      1  4  3  2  1
2      0  5  6  7  8

In [ ]:
df3.loc[2] # da error, porque no ha modificado el DataFrame, por lo que no existe el indice 2

KeyError: 2

In [29]:
df3 = pd.concat([df1, df2], axis=0)
df3.reset_index(inplace=True)
print(df3.reset_index(inplace=True))

None

In [30]:
df3.loc[2]

level_0    2
index      0
A          5
B          6
C          7
D          8
Name: 2, dtype: int64

In [32]:
df3 = pd.concat([df1, df2], axis=0)
df3

   A  B  C  D
0  1  2  3  4
1  4  3  2  1
0  5  6  7  8

In [ ]:
pd.concat([df1, df2],axis=1) # si hago un concat no puedo tener ni picos ni huecos

   A  B  C  D    A    B    C    D
0  1  2  3  4  5.0  6.0  7.0  8.0
1  4  3  2  1  NaN  NaN  NaN  NaN

In [38]:
df1 = pd.DataFrame([[1,2,3,4], [4,3,2,1]], columns = ["A", "B", "C", "D"])
df2 = pd.DataFrame([[5,6,7,8]], columns= ["A", "B", "C", "D"])
pd.concat([df1, df2], axis = 0).stack().iloc[0:4] #[: "A"]
# quiero empezar por el indice 0 y no quiero llegar al indice 4. El indice 0, es el indice (0,A), el siguiente (0,B), el indice 3 es el (0,D). 
# Esto es porque tengo índices multinivel

0  A    1
   B    2
   C    3
   D    4
dtype: int64

In [ ]:
pd.concat([df1, df2], axis = 0).stack().loc[0] # esto es para el indice 0, que tienen indice 0

A    1
B    2
C    3
D    4
A    5
B    6
C    7
D    8
dtype: int64

In [42]:
s4 = pd.concat([df1, df2], axis = 0).stack()
s4

0  A    1
   B    2
   C    3
   D    4
1  A    4
   B    3
   C    2
   D    1
0  A    5
   B    6
   C    7
   D    8
dtype: int64

In [47]:
s4.reset_index() # tengo que resetear los indices porque tengo indices duplicados. ajpra temgp que hacer una máscara booleana
s5 = s4.reset_index()

In [ ]:
s5.level_0 == 0 # lo que me dice quien tiene level 0

0      True
1      True
2      True
3      True
4     False
5     False
6     False
7     False
8      True
9      True
10     True
11     True
Name: level_0, dtype: bool

In [ ]:
s5.level_1 # esto es la serie

0     A
1     B
2     C
3     D
4     A
5     B
6     C
7     D
8     A
9     B
10    C
11    D
Name: level_1, dtype: str

In [50]:
cond_1 = (s5.level_0 == 0)
cond_2 = (s5.level_1 == "A") | (s5.level_1 == "B")

In [63]:
import pandas as pd
import numpy as np

For convenience, we'll define this function which creates a ``DataFrame`` of a particular form that will be useful below:

In [ ]:
def make_df(cols, ind):
    """Quickly make a DataFrame"""
    data = {c: [str(c) + str(i) for i in ind] # es un diccionario
            for c in cols}
    return pd.DataFrame(data, ind)

# example DataFrame
make_df('ABC', range(3)) # tengo una matriz 3x3

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In addition, we'll create a quick class that allows us to display multiple ``DataFrame``s side by side. The code makes use of the special ``_repr_html_`` method, which IPython uses to implement its rich object display:

In [ ]:
class display(object): # este codigo es para definir una clase
    """Display HTML representation of multiple objects"""
    template = """<div style="float: left; padding: 10px;">
    <p style='font-family:"Courier New", Courier, monospace'>{0}</p>{1}
    </div>"""
    def __init__(self, *args):
        self.args = args
        
    def _repr_html_(self):
        return '\n'.join(self.template.format(a, eval(a)._repr_html_()) 
                         for a in self.args)
    
    def __repr__(self):
        return '\n\n'.join(a + '\n' + repr(eval(a))
                           for a in self.args)

In [ ]:
eval("2+3") # eval = evaluate --> te paso un string y ejecutalo como si fuese python

5

In [77]:

df_nuevo = pd.concat([df1, df2],axis=1)
df_nuevo.index = ["a", "b"]
df_nuevo.columns = df_nuevo.columns.str.lower()
df_nuevo

   a  b  c  d    a    b    c    d
a  1  2  3  4  5.0  6.0  7.0  8.0
b  4  3  2  1  NaN  NaN  NaN  NaN

In [79]:
df7 = pd.concat([df1, df2],axis=1)
df7

   A  B  C  D    A    B    C    D
0  1  2  3  4  5.0  6.0  7.0  8.0
1  4  3  2  1  NaN  NaN  NaN  NaN

In [81]:
df7['ultimo_A'] = df7.loc[:,"A"].iloc[:, -1].isna() # isna --> es un missing, me va a dar una máscara booleano
df7['ultimo_A']

0    False
1     True
Name: ultimo_A, dtype: bool

In [ ]:
relleno = df7.loc[:,"A"].iloc[:, -1].mean()
relleno # la media es 5

np.float64(5.0)

In [ ]:
df7['ultimo_A'] = df7.loc[:,"A"].iloc[:, -1].isna() # isna --> es un missing
relleno = df7.loc[:,"A"].iloc[:, -1].mean()
df7.loc[:,"A"].iloc[:, -1].fillna(relleno, inplace=True) # lo que hago, es que el valor missing lo relleno con fillna. Pero me devuelve una copia.

In [83]:
trozo= df7.loc[:,"A"].iloc[:, -1]

relleno = df7.loc[:,"A"].iloc[:, -1].mean()

trozo.fillna(relleno, inplace=True)

trozo

0    5.0
1    5.0
Name: A, dtype: float64

In [ ]:
df7 # el original no te lo cambia

   A  B  C  D    A    B    C    D  ultimo_A
0  1  2  3  4  5.0  6.0  7.0  8.0     False
1  4  3  2  1  NaN  NaN  NaN  NaN      True

In [ ]:
test = pd.DataFrame() # tengo un DataFrame cuya columnas que son strings, y me interesa poder usar los métodos de los strings (suele pasar mucho con fechas)
test['color'] = ["rojo", "verde", "azul", "rojo"]
# si a un DataFrame, cojo una columna y la extraigo, obtengo una serie.
test.color.str.upper() # si yo tengo una columna que son strings, para poder usar los métodos de los strings, le tengo que meter 'str' para poder usar sus métodos

#test

0     ROJO
1    VERDE
2     AZUL
3     ROJO
Name: color, dtype: str

In [ ]:
test = pd.DataFrame() # tengo un DataFrame cuya columnas que son strings, y me interesa poder usar los métodos de los strings (suele pasar mucho con fechas, se tiene que poner dt = datetime)
test['color'] = ["rojo", "verde", "azul", "rojo"]
test['mayúsculas'] = test.color.str.upper()
test['reemplazo'] = test.mayúsculas.str.replace("E", "ZZZ")
test

   color mayúsculas  reemplazo
0   rojo       ROJO       ROJO
1  verde      VERDE  VZZZRDZZZ
2   azul       AZUL       AZUL
3   rojo       ROJO       ROJO

In [ ]:
una = [] 
otra = []

una.append(otra) = [[]] # a la lista 'una' le añades en el último elemento otra lista, 'otra'. Por lo que , ahora una tiene un elemento, que es 'otra', que es una lista vacia
otra.append(una) = [[]]

In [ ]:
mi_lista = []
mi_lista.append(mi_lista)
mi_lista # solo tengo un único objeto (una lista), que contiene 'x' objetos (se contiene a sí misma). Es una referencia cruzada.

[[...]]

In [62]:
mi_lista[0][0][0][0][0][0][0][0][0][0][0][0][0][0][0][0][0][0][0][0][0] is mi_lista

True

The use of this will become clearer as we continue our discussion in the following section.

## Recall: Concatenation of NumPy Arrays

Concatenation of ``Series`` and ``DataFrame`` objects is very similar to concatenation of Numpy arrays, which can be done via the ``np.concatenate`` function as discussed in [The Basics of NumPy Arrays](02.02-The-Basics-Of-NumPy-Arrays.ipynb).
Recall that with it, you can combine the contents of two or more arrays into a single array:

In [ ]:
x = [1,2,3]
y = [4,5,6]
z= [7,8,9]
np.concatenate([    [x],[y],[z]    ], axis = 0) # quiero pegar abajo y luego a la derecha. Concatenate de pandas es diferente que el de numpy
# el concatenate de numpy recibe listas de numpy arrays. Si no me dices nada, el axis=0

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
cubo = np.ones((3,3,3))
plano = np.zeros((3,3))

np.concatenate([cubo, plano[np.newaxis,:]])

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [66]:
df = pd.DataFrame(np.zeros((3,3)))
df

     0    1    2
0  0.0  0.0  0.0
1  0.0  0.0  0.0
2  0.0  0.0  0.0

In [14]:
#df.applymap(int) # applymap está obsoleto!!

In [67]:
df = pd.DataFrame()
df["A"] = [1,2,3,4,5]
df["B"] = [11, 12, 13, 14, 15]
df

   A   B
0  1  11
1  2  12
2  3  13
3  4  14
4  5  15

In [ ]:
df2["A"] = [1,2,3,4,5]
df2['B'] = [6,7,8,9,10]

In [ ]:
df['B'].apply(lambda x : x**2) # apply es un método de las series porque estas yendo a la columna "B" de un dataframe

0    121
1    144
2    169
3    196
4    225
Name: B, dtype: int64

In [ ]:
f3 = lambda x: x + 2 # lambda es una palabra reservada de python que sirve para hacer funciones, funciones lambda.
f3(5)

7

In [70]:
list(map(lambda x: x + 2, [4,5,6]))

[6, 7, 8]

In [ ]:
import math

df['B'].apply(math.sqrt) # tengo el dataframe y tengo la columna 'B', y ahora necesito una funcion. 
# Este resultado ya es una serie, a la que se le puede aplicar cualqueir otra función

0    3.316625
1    3.464102
2    3.605551
3    3.741657
4    3.872983
Name: B, dtype: float64

In [72]:
'''
pandas.Series.apply
Series.apply(func, args=(), *, by_row='compat', **kwargs)[source]
Invoke function on values of Series.

Can be ufunc (a NumPy function that applies to the entire Series) or a Python function that only works on single values.

Parameters:
func: function ---> tienes que darme la función, la que quieras.
Python function or NumPy ufunc to apply.

args: tuple
Positional arguments passed to func after the series value.

by_row: False or “compat”, default “compat”
'''

"\npandas.Series.apply\nSeries.apply(func, args=(), *, by_row='compat', **kwargs)[source]\nInvoke function on values of Series.\n\nCan be ufunc (a NumPy function that applies to the entire Series) or a Python function that only works on single values.\n\nParameters:\nfunc: function ---> tienes que darme la función, la que quieras.\nPython function or NumPy ufunc to apply.\n\nargs: tuple\nPositional arguments passed to func after the series value.\n\nby_row: False or “compat”, default “compat”\n"

In [73]:
df['B'] ** 2

0    121
1    144
2    169
3    196
4    225
Name: B, dtype: int64

In [74]:
df + 2

   A   B
0  3  13
1  4  14
2  5  15
3  6  16
4  7  17

In [85]:
# si hago la media por filas, me da una columna
# si hago la media por columnas, me da una fila

In [ ]:
df.A.map(lambda x: x+2) # en series el apply y el map no se utilizan mucho, porque tengo solo una dimension

0    3
1    4
2    5
3    6
4    7
Name: A, dtype: int64

In [20]:
df.A + 2

0    3
1    4
2    5
3    6
4    7
Name: A, dtype: int64

In [21]:
df.A.apply(lambda x: x+2)

0    3
1    4
2    5
3    6
4    7
Name: A, dtype: int64

In [22]:
df["palabras"] = ["a","b","c","d","e"]
df

   A   B palabras
0  1  11        a
1  2  12        b
2  3  13        c
3  4  14        d
4  5  15        e

In [23]:
df.palabras = df["palabras"].apply(str.upper)
df

   A   B palabras
0  1  11        A
1  2  12        B
2  3  13        C
3  4  14        D
4  5  15        E

In [24]:
1+1

2

In [25]:
df2 = pd.DataFrame()
df2['A'] = [1,2,3,4,5]
df2['B'] = [6,7,8,9,10]
df2

   A   B
0  1   6
1  2   7
2  3   8
3  4   9
4  5  10

In [26]:
#df.apply(lambda x: x**2)
df2.apply(lambda x: x*1.)
df['A'] = df2.A.apply(lambda x: x*1.)

The first argument is a list or tuple of arrays to concatenate.
Additionally, it takes an ``axis`` keyword that allows you to specify the axis along which the result will be concatenated:

In [27]:
x = [[1,2],
     [3,4]]
np.concatenate([x,x], axis = 1)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

## Simple Concatenation with ``pd.concat``

Pandas has a function, ``pd.concat()``, which has a similar syntax to ``np.concatenate`` but contains a number of options that we'll discuss momentarily:

```python
# Signature in Pandas v0.18
pd.concat(objs, axis=0, join='outer', join_axes=None, ignore_index=False,
          keys=None, levels=None, names=None, verify_integrity=False,
          copy=True)
```

``pd.concat()`` can be used for a simple concatenation of ``Series`` or ``DataFrame`` objects, just as ``np.concatenate()`` can be used for simple concatenations of arrays:

In [75]:
import numpy as np
import pandas as pd

In [ ]:
# left.join --> tengos 2 tablas (A y B), no quiero perder nada de la tabla A, si en la tabla B no hay dato me pones un missing value. 
# right.join --> al revés
# full.outer.join --> lo quiero todo (si estás en la tabla A, me lo das; si estás en la A pero no en la B, pones missing value, si apareces en las 2, me das los valores)
# inner.join --> solo me quedo con los datos que estén en las dos listas
# full.outer.join y inner.join se utilizan mucho en negocios

In [ ]:
s1 = pd.Series([11,22,33])
s2 = s1.copy()*5
pd.concat([s1,s2], verify_integrity= False) # verify_integrity --> es saber si son unicos; al poner = False, quiero decir que no me importa

0     11
1     22
2     33
0     55
1    110
2    165
dtype: int64

In [86]:
s1 = pd.Series([11,22,33])
s2 = s1.copy()
s3 = pd.concat([s1,s2]).reset_index(drop = True)
s3.drop_duplicates()

0    11
1    22
2    33
dtype: int64

In [87]:
s3

0    11
1    22
2    33
3    11
4    22
5    33
dtype: int64

In [88]:
ser1 = pd.Series(['A', 'B', 'C'], index=[1,2,3])
ser2 = pd.Series(['D', 'E', 'F'], index=[4,5,6])
pd.concat([ser1, ser2], axis = 0)

1    A
2    B
3    C
4    D
5    E
6    F
dtype: str

It also works to concatenate higher-dimensional objects, such as ``DataFrame``s:

In [ ]:
df1 = make_df('AB', [1,3])
df2 = make_df('AC', [3,4])
display('df1', 'df2', 'pd.concat([df1, df2], axis = 1, join = "inner")') 
# concatenar df1, df2; axis=1 es por columnas, y join=inner; solo lis valores que estén en ambas tablas. Si en vez de inner, pongo outter, quiero todo

df1
    A   B
1  A1  B1
3  A3  B3

df2
    A   C
3  A3  C3
4  A4  C4

pd.concat([df1, df2], axis = 1, join = "inner")
    A   B   A   C
3  A3  B3  A3  C3

In [91]:
df1 = make_df('AB', [1,2,3])
df2 = make_df('ABC', [3,4,5])
display('df1', 'df2', 'pd.concat([df1, df2], axis = 0)') # axis=0, pega filas hacia abajo

df1
    A   B
1  A1  B1
2  A2  B2
3  A3  B3

df2
    A   B   C
3  A3  B3  C3
4  A4  B4  C4
5  A5  B5  C5

pd.concat([df1, df2], axis = 0)
    A   B    C
1  A1  B1  NaN
2  A2  B2  NaN
3  A3  B3  NaN
3  A3  B3   C3
4  A4  B4   C4
5  A5  B5   C5

In [ ]:
display('df1', 'df2', 'pd.concat([df1, df2], axis = 1, join = "inner")') # como es axis=1, sale una matriz 1x4 (el mismo nº de columnas que tengo y luego las filas)

'df1'

'df2'

'pd.concat([df1, df2], axis = 1, join = "inner")'

In [93]:
df_otro = df.copy()
df_otro.loc[1,"palabras"] = "A"
df_otro

   A   B palabras
0  1  11      NaN
1  2  12        A
2  3  13      NaN
3  4  14      NaN
4  5  15      NaN

In [94]:
pd.concat([df, df_otro])

   A   B palabras
0  1  11      NaN
1  2  12      NaN
2  3  13      NaN
3  4  14      NaN
4  5  15      NaN
0  1  11      NaN
1  2  12        A
2  3  13      NaN
3  4  14      NaN
4  5  15      NaN

By default, the concatenation takes place row-wise within the ``DataFrame`` (i.e., ``axis=0``).
Like ``np.concatenate``, ``pd.concat`` allows specification of an axis along which concatenation will take place.
Consider the following example:

In [37]:
df3 = make_df('AB', [0,1])
df4 = make_df('CD', [0,1])
display('df3', 'df4', "pd.concat([df3, df4], axis=0)")

df3
    A   B
0  A0  B0
1  A1  B1

df4
    C   D
0  C0  D0
1  C1  D1

pd.concat([df3, df4], axis=0)
     A    B    C    D
0   A0   B0  NaN  NaN
1   A1   B1  NaN  NaN
0  NaN  NaN   C0   D0
1  NaN  NaN   C1   D1

We could have equivalently specified ``axis=1``; here we've used the more intuitive ``axis='col'``.

### Duplicate indices

One important difference between ``np.concatenate`` and ``pd.concat`` is that Pandas concatenation *preserves indices*, even if the result will have duplicate indices!
Consider this simple example:

In [38]:
x = make_df('AB', [0, 1])
y = make_df('AB', [2, 3])
y.index = x.index  # make duplicate indices!
display('x', 'y', 'pd.concat([x, y])')

x
    A   B
0  A0  B0
1  A1  B1

y
    A   B
0  A2  B2
1  A3  B3

pd.concat([x, y])
    A   B
0  A0  B0
1  A1  B1
0  A2  B2
1  A3  B3

Notice the repeated indices in the result.
While this is valid within ``DataFrame``s, the outcome is often undesirable.
``pd.concat()`` gives us a few ways to handle it.

#### Catching the repeats as an error

If you'd like to simply verify that the indices in the result of ``pd.concat()`` do not overlap, you can specify the ``verify_integrity`` flag.
With this set to True, the concatenation will raise an exception if there are duplicate indices.
Here is an example, where for clarity we'll catch and print the error message:

In [39]:
try:
    pd.concat([x,y], verify_integrity=True)
except ValueError as e:
        print("ValueError:", e)

ValueError: Indexes have overlapping values: Index([0, 1], dtype='int64')

#### Ignoring the index

Sometimes the index itself does not matter, and you would prefer it to simply be ignored.
This option can be specified using the ``ignore_index`` flag.
With this set to true, the concatenation will create a new integer index for the resulting ``Series``:

In [40]:
display('x', 'y', 'pd.concat([x, y], ignore_index=True)')

x
    A   B
0  A0  B0
1  A1  B1

y
    A   B
0  A2  B2
1  A3  B3

pd.concat([x, y], ignore_index=True)
    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3

#### Adding MultiIndex keys

Another option is to use the ``keys`` option to specify a label for the data sources; the result will be a hierarchically indexed series containing the data:

In [41]:
display('x', 'y', "pd.concat([x, y], keys=['xaaa', 'yuu'])")

x
    A   B
0  A0  B0
1  A1  B1

y
    A   B
0  A2  B2
1  A3  B3

pd.concat([x, y], keys=['xaaa', 'yuu'])
         A   B
xaaa 0  A0  B0
     1  A1  B1
yuu  0  A2  B2
     1  A3  B3

The result is a multiply indexed ``DataFrame``, and we can use the tools discussed in [Hierarchical Indexing](03.05-Hierarchical-Indexing.ipynb) to transform this data into the representation we're interested in.

### Concatenation with joins

In the simple examples we just looked at, we were mainly concatenating ``DataFrame``s with shared column names.
In practice, data from different sources might have different sets of column names, and ``pd.concat`` offers several options in this case.
Consider the concatenation of the following two ``DataFrame``s, which have some (but not all!) columns in common:

In [42]:
df5 = make_df('ABC', [1, 2])
df6 = make_df('BCD', [3, 4])
display('df5', 'df6', 'pd.concat([df5, df6])')

df5
    A   B   C
1  A1  B1  C1
2  A2  B2  C2

df6
    B   C   D
3  B3  C3  D3
4  B4  C4  D4

pd.concat([df5, df6])
     A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4

By default, the entries for which no data is available are filled with NA values.
To change this, we can specify one of several options for the ``join`` and ``join_axes`` parameters of the concatenate function.
By default, the join is a union of the input columns (``join='outer'``), but we can change this to an intersection of the columns using ``join='inner'``:

In [43]:
display('df5', 'df6',
        "pd.concat([df5, df6], join='inner')")

df5
    A   B   C
1  A1  B1  C1
2  A2  B2  C2

df6
    B   C   D
3  B3  C3  D3
4  B4  C4  D4

pd.concat([df5, df6], join='inner')
    B   C
1  B1  C1
2  B2  C2
3  B3  C3
4  B4  C4

The combination of options of the ``pd.concat`` function allows a wide range of possible behaviors when joining two datasets; keep these in mind as you use these tools for your own data.