### Introduction:

The following exercise utilizes data from [UC Irvine Machine Learning Repository](https://archive.ics.uci.edu/ml/datasets/Auto+MPG)

### Step 1. Import the necessary libraries

In [1]:
import numpy as np
import pandas as pd

### Step 2. Import the first dataset [cars1](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars1.csv) and [cars2](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars2.csv).

In [2]:
coche1 = "https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars1.csv"
coche2 = "https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars2.csv"

   ### Step 3. Assign each to a to a variable called cars1 and cars2

In [3]:
cars1 = pd.read_csv(coche1, sep=",")
cars2 = pd.read_csv(coche2, sep=",")

### Step 4. Oops, it seems our first dataset has some unnamed blank columns, fix cars1

In [4]:
cars1

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,NaN,NaN,NaN,NaN,NaN
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,NaN,NaN,NaN,NaN,NaN
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,NaN,NaN,NaN,NaN,NaN
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,NaN,NaN,NaN,NaN,NaN
4,17.0,8,302,140,3449,10.5,70,1,ford torino,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,24.0,6,200,81,3012,17.6,76,1,ford maverick,NaN,NaN,NaN,NaN,NaN
194,22.5,6,232,90,3085,17.6,76,1,amc hornet,NaN,NaN,NaN,NaN,NaN
195,29.0,4,85,52,2035,22.2,76,1,chevrolet chevette,NaN,NaN,NaN,NaN,NaN
196,24.5,4,98,60,2164,22.1,76,1,chevrolet woody,NaN,NaN,NaN,NaN,NaN
197,29.0,4,90,70,1937,14.2,76,2,vw rabbit,NaN,NaN,NaN,NaN,NaN

In [5]:
# si uso isna, isnull -> me dice si hay valores nulos/missing values. Pero me queda saber, si en todos los datos son missing values o no. 
# Para ello, usamos isnull().all()
cars1.isnull().all()

mpg             False
cylinders       False
displacement    False
horsepower      False
weight          False
acceleration    False
model           False
origin          False
car             False
Unnamed: 9       True
Unnamed: 10      True
Unnamed: 11      True
Unnamed: 12      True
Unnamed: 13      True
dtype: bool

In [6]:
# con loc, puedo eliminar las columnas sabiendo el nombre de las columnas. Quiero todas las filas, y todas las columnas hasta "car"
cars1.loc[:, :'car']

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
193,24.0,6,200,81,3012,17.6,76,1,ford maverick
194,22.5,6,232,90,3085,17.6,76,1,amc hornet
195,29.0,4,85,52,2035,22.2,76,1,chevrolet chevette
196,24.5,4,98,60,2164,22.1,76,1,chevrolet woody
197,29.0,4,90,70,1937,14.2,76,2,vw rabbit

In [7]:
cars2

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,33.0,4,91,53,1795,17.4,76,3,honda civic
1,20.0,6,225,100,3651,17.7,76,1,dodge aspen se
2,18.0,6,250,78,3574,21.0,76,1,ford granada ghia
3,18.5,6,250,110,3645,16.2,76,1,pontiac ventura sj
4,17.5,6,258,95,3193,17.8,76,1,amc pacer d/l
...,...,...,...,...,...,...,...,...,...
195,27.0,4,140,86,2790,15.6,82,1,ford mustang gl
196,44.0,4,97,52,2130,24.6,82,2,vw pickup
197,32.0,4,135,84,2295,11.6,82,1,dodge rampage
198,28.0,4,120,79,2625,18.6,82,1,ford ranger
199,31.0,4,119,82,2720,19.4,82,1,chevy s-10

mpg             False
cylinders       False
displacement    False
horsepower      False
weight          False
acceleration    False
model           False
origin          False
car             False
Unnamed: 9       True
Unnamed: 10      True
Unnamed: 11      True
Unnamed: 12      True
Unnamed: 13      True
dtype: bool

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
193,24.0,6,200,81,3012,17.6,76,1,ford maverick
194,22.5,6,232,90,3085,17.6,76,1,amc hornet
195,29.0,4,85,52,2035,22.2,76,1,chevrolet chevette
196,24.5,4,98,60,2164,22.1,76,1,chevrolet woody
197,29.0,4,90,70,1937,14.2,76,2,vw rabbit

### Step 5. What is the number of observations in each dataset?

In [8]:
cars1.shape

(198, 14)

In [9]:
cars2.shape

(200, 9)

(198, 14)
(200, 9)

### Step 6. Join cars1 and cars2 into a single DataFrame called cars

In [12]:
cars = pd.concat([cars1, cars2], axis=0)
cars

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,NaN,NaN,NaN,NaN,NaN
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,NaN,NaN,NaN,NaN,NaN
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,NaN,NaN,NaN,NaN,NaN
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,NaN,NaN,NaN,NaN,NaN
4,17.0,8,302,140,3449,10.5,70,1,ford torino,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,27.0,4,140,86,2790,15.6,82,1,ford mustang gl,NaN,NaN,NaN,NaN,NaN
196,44.0,4,97,52,2130,24.6,82,2,vw pickup,NaN,NaN,NaN,NaN,NaN
197,32.0,4,135,84,2295,11.6,82,1,dodge rampage,NaN,NaN,NaN,NaN,NaN
198,28.0,4,120,79,2625,18.6,82,1,ford ranger,NaN,NaN,NaN,NaN,NaN
199,31.0,4,119,82,2720,19.4,82,1,chevy s-10,NaN,NaN,NaN,NaN,NaN

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,NaN,NaN,NaN,NaN,NaN
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,NaN,NaN,NaN,NaN,NaN
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,NaN,NaN,NaN,NaN,NaN
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,NaN,NaN,NaN,NaN,NaN
4,17.0,8,302,140,3449,10.5,70,1,ford torino,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,27.0,4,140,86,2790,15.6,82,1,ford mustang gl,NaN,NaN,NaN,NaN,NaN
196,44.0,4,97,52,2130,24.6,82,2,vw pickup,NaN,NaN,NaN,NaN,NaN
197,32.0,4,135,84,2295,11.6,82,1,dodge rampage,NaN,NaN,NaN,NaN,NaN
198,28.0,4,120,79,2625,18.6,82,1,ford ranger,NaN,NaN,NaN,NaN,NaN
199,31.0,4,119,82,2720,19.4,82,1,chevy s-10,NaN,NaN,NaN,NaN,NaN

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,NaN,NaN,NaN,NaN,NaN
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,NaN,NaN,NaN,NaN,NaN
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,NaN,NaN,NaN,NaN,NaN
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,NaN,NaN,NaN,NaN,NaN
4,17.0,8,302,140,3449,10.5,70,1,ford torino,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
393,27.0,4,140,86,2790,15.6,82,1,ford mustang gl,NaN,NaN,NaN,NaN,NaN
394,44.0,4,97,52,2130,24.6,82,2,vw pickup,NaN,NaN,NaN,NaN,NaN
395,32.0,4,135,84,2295,11.6,82,1,dodge rampage,NaN,NaN,NaN,NaN,NaN
396,28.0,4,120,79,2625,18.6,82,1,ford ranger,NaN,NaN,NaN,NaN,NaN
397,31.0,4,119,82,2720,19.4,82,1,chevy s-10,NaN,NaN,NaN,NaN,NaN

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,NaN,NaN,NaN,NaN,NaN
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,NaN,NaN,NaN,NaN,NaN
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,NaN,NaN,NaN,NaN,NaN
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,NaN,NaN,NaN,NaN,NaN
4,17.0,8,302,140,3449,10.5,70,1,ford torino,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,27.0,4,140,86,2790,15.6,82,1,ford mustang gl,NaN,NaN,NaN,NaN,NaN
196,44.0,4,97,52,2130,24.6,82,2,vw pickup,NaN,NaN,NaN,NaN,NaN
197,32.0,4,135,84,2295,11.6,82,1,dodge rampage,NaN,NaN,NaN,NaN,NaN
198,28.0,4,120,79,2625,18.6,82,1,ford ranger,NaN,NaN,NaN,NaN,NaN
199,31.0,4,119,82,2720,19.4,82,1,chevy s-10,NaN,NaN,NaN,NaN,NaN

### Step 7. Oops, there is a column missing, called owners. Create a random number Series from 15,000 to 73,000.

In [13]:
import random

In [19]:
valores = np.random.randint(15000,73000,size=398)
owner = pd.Series(valores)

In [20]:
cars['owner'] = pd.Series(valores)
cars

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,owner
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,NaN,NaN,NaN,NaN,NaN,62994
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,NaN,NaN,NaN,NaN,NaN,71563
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,NaN,NaN,NaN,NaN,NaN,70161
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,NaN,NaN,NaN,NaN,NaN,16441
4,17.0,8,302,140,3449,10.5,70,1,ford torino,NaN,NaN,NaN,NaN,NaN,50509
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,27.0,4,140,86,2790,15.6,82,1,ford mustang gl,NaN,NaN,NaN,NaN,NaN,66577
196,44.0,4,97,52,2130,24.6,82,2,vw pickup,NaN,NaN,NaN,NaN,NaN,42956
197,32.0,4,135,84,2295,11.6,82,1,dodge rampage,NaN,NaN,NaN,NaN,NaN,49390
198,28.0,4,120,79,2625,18.6,82,1,ford ranger,NaN,NaN,NaN,NaN,NaN,27224
199,31.0,4,119,82,2720,19.4,82,1,chevy s-10,NaN,NaN,NaN,NaN,NaN,20813

(398,)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,owner
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,NaN,NaN,NaN,NaN,NaN,52424
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,NaN,NaN,NaN,NaN,NaN,44668
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,NaN,NaN,NaN,NaN,NaN,35643
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,NaN,NaN,NaN,NaN,NaN,48149
4,17.0,8,302,140,3449,10.5,70,1,ford torino,NaN,NaN,NaN,NaN,NaN,49329
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,27.0,4,140,86,2790,15.6,82,1,ford mustang gl,NaN,NaN,NaN,NaN,NaN,64171
196,44.0,4,97,52,2130,24.6,82,2,vw pickup,NaN,NaN,NaN,NaN,NaN,24845
197,32.0,4,135,84,2295,11.6,82,1,dodge rampage,NaN,NaN,NaN,NaN,NaN,69233
198,28.0,4,120,79,2625,18.6,82,1,ford ranger,NaN,NaN,NaN,NaN,NaN,35276
199,31.0,4,119,82,2720,19.4,82,1,chevy s-10,NaN,NaN,NaN,NaN,NaN,49921

### Step 8. Add the column owners to cars

In [ ]:
cars3 = pd.Series(valores)
owners = cars3.to_frame()

InvalidIndexError: Reindexing only valid with uniquely valued Index objects

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,ownsers,owners
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,NaN,NaN,NaN,NaN,NaN,53251,27606
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,NaN,NaN,NaN,NaN,NaN,59422,49090
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,NaN,NaN,NaN,NaN,NaN,37971,67750
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,NaN,NaN,NaN,NaN,NaN,26677,51476
4,17.0,8,302,140,3449,10.5,70,1,ford torino,NaN,NaN,NaN,NaN,NaN,36778,23633
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,27.0,4,140,86,2790,15.6,82,1,ford mustang gl,NaN,NaN,NaN,NaN,NaN,60497,63289
196,44.0,4,97,52,2130,24.6,82,2,vw pickup,NaN,NaN,NaN,NaN,NaN,21235,37321
197,32.0,4,135,84,2295,11.6,82,1,dodge rampage,NaN,NaN,NaN,NaN,NaN,17390,51911
198,28.0,4,120,79,2625,18.6,82,1,ford ranger,NaN,NaN,NaN,NaN,NaN,59976,36185
199,31.0,4,119,82,2720,19.4,82,1,chevy s-10,NaN,NaN,NaN,NaN,NaN,28733,71615